name: build
on:
  pull_request:
    branches: 
      - main
      - master
      - develop
  push:
    branches: 
      - main
      - master
      - develop
      - status-box

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.13, 1.14, 1.15]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Running go tests
      env:
        GO111MODULE: on
      run: make tests
    - name: Coverage report upload
      uses: codecov/codecov-action@v1
      with: 
        fail_ci_if_error: false

  build:
    name: "Build package"
    needs: "test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        go: [1.13, 1.14, 1.15]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code
        uses: actions/checkout@master
      - name: Build
        env: 
          GO111MODULE: on
        run: make all


  # examples:
  #   name: Build examples
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Go 1.14
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.14
  #       id: go
  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@master
  #     - name: Building go examples
  #       env:
  #         GO111MODULE: on
  #       run: ./_example/build.sh

  # lint:
  #   name: Run lint checks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Go 1.14
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.14
  #       id: go
  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@master
  #     - name: Download golangci-lint
  #       run: |
  #         wget https://github.com/golangci/golangci-lint/releases/download/v1.31.0/golangci-lint-1.31.0-linux-amd64.tar.gz
  #         tar -xvf ./golangci-lint-1.31.0-linux-amd64.tar.gz
  #     - name: Running golangci-lint
  #       env:
  #         GO111MODULE: on
  #         GOPATH: /home/runner/work/
  #       run: GOCILINT=./golangci-lint-1.31.0-linux-amd64/golangci-lint make lint
