name: release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@master
      - name: Build
        env:
          GO111MODULE: on
        run: make all
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
    
