name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true


jobs:
  build:
    name: Create release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@master
      - name: Build
        env:
          GO111MODULE: on
        run: make all
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
    
